debug: true

security:
  sessions: ALWAYS
  ignored: /webjars/**
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: test-clientId
      client-secret: test-clientId-secret-123
      access-token-uri: http://localhost:8082/uaa/oauth/token
      user-authorization-uri: http://localhost:8082/uaa/oauth/authorize
#      clientAuthenticationScheme: form
    resource:
#      userInfoUri: http://localhost:8082/me
      token-info-uri: http://localhost:8082/uaa/oauth/check_token
      prefer-token-info: true
      
logging:
  level:
    org.springframework.security: DEBUG